---
title: Planning thoughts for Quant UX Con 2023
author: Chris Chapman
date: '2023-03-01'
slug: []
categories: []
tags: []
---

Quant UX Con started in June 2022. 
It is the first-ever conference devoted to the practice of Quant UX research.
Quant UX Con 2023 will occur June 14-15 online, worldwide, in all time zones.

In 2022, we planned the first year to occur in person and expected 200 attendees.
But when the number of interested 
sign-ups passed 1000 we realized a new plan was needed. 
So we pivoted to an almost-all-online format and ended up with more 
than _2500_ attendees, plus 12 in-person watch parties across the US and Europe.

You might wonder, how engaged were the attendees? 
Did it match the energy of an in-person conference?
Being UX researchers, we have some data on that. 
The average logged-in time online was **7.5 hours** (a full day, _on average_ for 
each attendee!)
Top-2 box satisfaction was **79%**, on par with typical commercial products.
The number of submissions for 2023 has gone up, now at **2.5x** of the number for 2023.
And during sessions in 2022, attendee chat routinely exceeded the max chat messages that our
platform could handle!

What about the 21% of attendees who were only partially satisfied?
It's not a bad score, but the organizing committee itself was not fully satisfied.
Yes, first time events at this scale always have issues, and yes, 
worldwide CSat scores include some countries where users rarely rate things in the 
top 2 boxes. 
But we always want to improve.

The top 2 complaints were (1) wanting to have _recordings_ of the talks, and (2)
wanting it to expand to _non-US time zones._ 
Guess what?
We're doing exactly that for 2023.
Quant UX Con 2023 will use a follow-the-sun model
to have sessions live in every time zone worldwide, and we plan for _all_ talks
to be recorded for watching later (up to 3 months after the conference).

How much does all this cost? 
We're committed to making Quant UX Con _affordable for everyone interested._
Tickets for full admission --- all sessions, all time zones, all recordings ---
for Quant UX Con 2023 will cost USD $25.
_And_ there will be scholarship tickets, on the honor system --- no need to ask 
or prove anything --- for everyone who wants one.
This is made possible by our generous financial sponsors, **Pinterest, Meta, Ipsos, Sawtooth Software**,
and **Sprig**!

Interested? Visit the conference site and join the mailing 
list.
You'll get notification of registration when it is available in April:
[Quant UX Conference 2023](https://quantuxcon.org).

We hope to see you there!
